# Application configuration

database:
    driver: mysql
    url: root:engdawork9397@/eccomerce?charset=utf8mb4&parseTime=True


http_server:
   port: 9000

API_KEY: CHASECK_TEST-6jPr56w2AFvBgYKl2xrFyFCFIB4rynQR
