database:
  # url: postgres://postgres:engdawork9397@localhost:5432/defaultdb?sslmode=disable
  url: postgres://root@localhost:26257/defaultdb?sslmode=disable
  idle_conn_timeout: 8
  # url: root:engdawork9397@/eccomerce?charset=utf8mb4&parseTime=True
redis:
  redist_url: "redis://localhost:6379/0"
  subscriber: "payment_confirmation"
test_database:
  user: root
  password:
  host: localhost
  port: 26257  
migration:
  active: true
  seed_active: true
  path: internal/constant/query/schemas  
server:
  host:
  port: 8000
  timeout: 30s
  read_header_timeout: 30s
  retry:
    initial_interval: 2s
    randomization_factor: 0.2
    multiplier: 5
    max_interval: 24h
    max_elapsed_time: 168h
swagger: # swagger documentation endpoint configs
  schemes:
    - https
  host: pgbackend.a2p.et   
public_key: public.example.pem
private_key: private.example.pem 
service:
  authorization:
    db_name: "authz"
    host: http://206.189.54.235:5184
    service_id: f69d000b-ed62-4e77-91a3-4148ef9e12b7
    password: r5pJr#.ykZXKNMTskiq@
    admin: 7a628b40-8a65-4f6d-9a45-46b825feb4cb
    domain:
      system: 107250ac-4ab3-4afc-9730-8a2f33a41930
      merchant: 51ec08bd-88ab-4a53-a342-825445c7597a
      user: 51ec08bd-88ab-4a53-a342-825445c75975
  accounting:
    db_name: "accounting"
    url: "http://206.189.21.34"
    product_id: "b7a45a93-7efe-460c-8cbf-730cbe3bfbf0"
    secret: "12345"
    client:
      retry: 1
    chart_of_account:
      #Liability Accounts
      merchant_account: "2000-121c6671-fb0b-418b-8a8b-22972c535d9e"
      vat_account: "2000-67d3f3d0-5cf2-4852-a2ca-7437d84909cc"
      tax_account: "1000-feab249f-35b7-47d0-8637-363add8c6768"
      bank:
        in: "1000-770f5b7d-ecf0-4c71-a876-6fb9a836e058"
        out: "1000-143049da-27d6-469b-84bd-19e57b601e1e"
        bank_accounts: "1000-fabcc3fe-2531-45af-a97a-e69bbee8602a"
        telebirr_account:
          in: "1000-988ffb66-c2b5-481e-b10f-7a3560761093"
          out: "1000-c78d5359-a57c-48ab-8896-4db720a821f7"
        airtime_account:
          in: "1000-988ffb66-c2b5-481e-b10f-7a3560761093"
          out: "1000-c78d5359-a57c-48ab-8896-4db720a821f7"
        enat_bank_account:
          in: "1000-61900526-bdfc-4ed1-a059-5a86aa259f67"
          out: "1000-dd63fb93-77dc-4381-89df-aced09d44ff3"
        cbe_account:
          cbe_birr_cash_in: "1000-4ab9ea3a-9139-4a24-982a-fcff429e877f"
          cbe_mobile_cash_in: "1000-0096bdf4-bb3c-4748-898b-52c4e31cb8fd"
        mpesa_account:
          in: "1000-988ffb66-c2b5-481e-b10f-7a3560761093"
        amhara_bank_account:
          in: "1000-f73377b4-9f55-43bd-b8dc-bc49cf35e169"
        zemen_bank_account:
          in: "1000-7428e9d2-3025-45c8-a0a4-c35449000314"
        etswitch_account:
          in: "1000-988ffb66-c2b5-481e-b10f-7a3560761093"
      # Equity Accounts
      retained_earnings_account: "3000-0a77e575-d083-4e99-9bfd-5d554f8b5332"

      # Expense Accounts
      service_charge_account: "4000-5e41ba89-16e7-4015-9785-8c42563a46b4"
      reimbursement_account: "5000-e2cc0a83-fde9-4711-8f7a-49a903c72804"
      gift_account: "5000-ca100ec1-3ff9-433a-84de-8b26540cebc1"
      operational_cost_account: "5000"

      # Expense Accounts
      service_charge_account_custom: "4000-5e41ba89-16e7-4015-9785-8c42563a46b4"

      # Receivable Accounts
      receivable_account: "2000-121c6671-fb0b-418b-8a8b-22972c535d9e"
cron:
  spec:
    recurring_payment: "@every 30s"
    cancel_user_subscription: "@every 30m"
    payout: "@daily"
    cancel_user_subscription_at_period_end: "@every 30m"
    call_back_timer: "*/5 * * * *"
    expire_user_subscription:
      upper_limit: 1h
      lower_limit: 30m
      timer: "*/5 * * * *"
cors:
  origin:
    - http://localhost:8000
  allow_credentials: true
  headers:
    - Location
    - Content-Type
    - Options
    - Authorization
    - X-Requested-With
    - Access-Control-Allow-Headers
http:
  max_idle_conns_per_host: 100
  max_idle_conns: 100
  max_conns_per_host: 100
  timeout: 10s
platforms:
  chapa:
    secret_key: CHASECK_TEST-6jPr56w2AFvBgYKl2xrFyFCFIB4rynQR
    public_key: CHAPUBK_TEST-1qvKnbbAs1OftYZwqLdykGBc8vwvBUga
    test_secret_key: CHASECK_TEST-6jPr56w2AFvBgYKl2xrFyFCFIB4rynQR
    test_public_key: CHAPUBK_TEST-1qvKnbbAs1OftYZwqLdykGBc8vwvBUga
  cloudinary: 
    cloudinary_url: "cloudinary://828868553985341:GmQAncUhIfAWjOqQWFyXRHyFCCc@note-zipper" 
security_credential:
  symmetric_key: "abcdefghijklmnopqrstuvwxwz123456"
  issuer: "2fCapital-payment-gatewey"
  footer: "2fCapital-payment-gatewey-merchant-authentication-token"
  key_length: 12
  expire_at: 525600 # one year in minute
assets:
  - name: product_image
    types:
      - png
      - jpg
      - jpeg
    max_size: 2097152 
  - name: merchant_logo
    types:
      - png
      - jpg
      - jpeg
    max_size: 2097152 # bytes
  - name: merchant_license
    types:
      - pdf
      - doc
      - docx
      - jpg
    max_size: 2097152 # bytes
digital_ocean:
  space:
    key: key
    secret: secret
    url: url
    bucket: bucket


